#!/usr/bin/env bash

set -Eeuo pipefail
umask 077

if [[ ${EUID} -ne 0 ]]; then
  echo "error: this cutover must run as root" >&2
  exit 2
fi
if [[ $# -ne 3 ]]; then
  echo "usage: $0 CODE_SOURCE RELEASE_ID EXPECTED_USER_COUNT" >&2
  exit 2
fi

code_source=$(realpath "$1")
release_id=$2
expected_count=$3

if [[ ! ${release_id} =~ ^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$ ]]; then
  echo "error: unsafe release id: ${release_id}" >&2
  exit 2
fi
if [[ ! ${expected_count} =~ ^[1-9][0-9]*$ ]]; then
  echo "error: expected user count must be positive" >&2
  exit 2
fi

interface_python=/opt/interface-env/bin/python
mapping=/var/lib/potato-agent/config/users_mapping.yaml
data_dir=/var/lib/potato-agent/data
repo=/srv/potato_agent
base=/opt/potato-hermes-lite
release=${base}/releases/${release_id}
current=${base}/current
hermes_link=/usr/local/bin/hermes
interface_unit=potato-interface.service
interface_dropin=/etc/systemd/system/potato-interface.service.d/50-hermes-lite.conf
fingerprint_script=${code_source}/hermes-lite/scripts/fingerprint_state.py
refresh_script=${repo}/refresh_hermes_systemd_units.py

for path in \
  "${interface_python}" \
  "${mapping}" \
  "${release}/manifest.json" \
  "${release}/venv/bin/python3" \
  "${release}/venv/bin/hermes" \
  "${release}/config/runtime-profile.yaml" \
  "${release}/browser/bin/agent-browser" \
  "${release}/browser/chrome/chrome-linux64/chrome" \
  "${release}/browser/chrome/chrome-linux64/chrome-sandbox" \
  "${fingerprint_script}"; do
  if [[ ! -e ${path} ]]; then
    echo "error: required cutover path is missing: ${path}" >&2
    exit 2
  fi
done
if [[ ! -d ${code_source}/interface || ! -f ${code_source}/interface/app.py ]]; then
  echo "error: code source is incomplete: ${code_source}" >&2
  exit 2
fi
if find "${code_source}" -type l -print -quit | grep -q .; then
  echo "error: code source must not contain symlinks" >&2
  exit 2
fi
if find "${code_source}" -type f \( \
  -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' -o \
  -name '.env' -o -name '*.pyc' -o -name '*.pyo' \
\) -print -quit | grep -q .; then
  echo "error: code source contains runtime state or generated bytecode" >&2
  exit 2
fi
if [[ -e ${code_source}/users_mapping.yaml || -d ${code_source}/hermes-agent ]]; then
  echo "error: code source contains excluded legacy or mapping state" >&2
  exit 2
fi
if [[ ! -L ${hermes_link} ]]; then
  echo "error: existing Hermes compatibility entry is not a symlink" >&2
  exit 2
fi
if [[ -e ${current} && ! -L ${current} ]]; then
  echo "error: Lite current path exists but is not a symlink" >&2
  exit 2
fi

"${release}/venv/bin/pip" check >/dev/null
"${release}/venv/bin/hermes" --help >/dev/null
"${release}/venv/bin/python3" -I - "${release}" <<'PY'
import hashlib
import importlib.metadata
import json
import pathlib
import stat
import sys

root = pathlib.Path(sys.argv[1]).resolve()
site_root = (root / "venv").resolve()
manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
project = manifest.get("project")
if not isinstance(project, dict):
    raise SystemExit("release manifest project must be an object")
if project.get("name") != "potato-hermes-lite":
    raise SystemExit("release manifest project name mismatch")
expected_version = project.get("version")
if not isinstance(expected_version, str) or not expected_version:
    raise SystemExit("release manifest project version is invalid")
installed = {
    distribution.metadata["Name"].lower(): distribution.version
    for distribution in importlib.metadata.distributions()
    if distribution.metadata.get("Name")
}
if installed.get("potato-hermes-lite") != expected_version:
    raise SystemExit(
        "potato-hermes-lite version mismatch: "
        f"expected {expected_version}, got {installed.get('potato-hermes-lite')}"
    )
if "hermes-agent" in installed:
    raise SystemExit("legacy hermes-agent leaked into Lite venv")

import agent.codex_runtime
import potato_hermes_lite
import tui_gateway.entry

if potato_hermes_lite.__version__ != expected_version:
    raise SystemExit(
        "potato_hermes_lite.__version__ mismatch: "
        f"expected {expected_version}, got {potato_hermes_lite.__version__}"
    )
for module in (agent.codex_runtime, potato_hermes_lite, tui_gateway.entry):
    origin = pathlib.Path(module.__file__).resolve()
    if site_root not in origin.parents:
        raise SystemExit(f"module loaded outside Lite venv: {origin}")

wheel = root / "wheel" / manifest["wheel"]["filename"]
profile = root / manifest["runtime_profile"]["path"]
for path, expected in (
    (wheel, manifest["wheel"]["sha256"]),
    (profile, manifest["runtime_profile"]["sha256"]),
):
    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    if actual != expected:
        raise SystemExit(f"release hash mismatch: {path}")
sandbox = root / "browser/chrome/chrome-linux64/chrome-sandbox"
info = sandbox.stat()
if info.st_uid != 0 or stat.S_IMODE(info.st_mode) != 0o4755:
    raise SystemExit("Chrome sandbox must be root-owned mode 04755")
PY

mapfile -t mapped_services < <(
  "${interface_python}" - "${mapping}" <<'PY'
import pathlib
import re
import sys
import yaml

value = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")) or {}
services = []
for index, user in enumerate(value.get("users") or []):
    if not isinstance(user, dict):
        raise SystemExit(f"invalid mapping user at index {index}")
    service = str(user.get("systemd_service") or "").strip()
    if re.fullmatch(r"hermes-[A-Za-z0-9_.@-]+\.service", service) is None:
        raise SystemExit(f"missing or unsafe mapped service at index {index}")
    services.append(service)
if len(services) != len(set(services)):
    raise SystemExit("mapping contains duplicate Hermes services")
print("\n".join(sorted(services)))
PY
)
if [[ ${#mapped_services[@]} -ne ${expected_count} ]]; then
  echo "error: expected ${expected_count} mapped services, found ${#mapped_services[@]}" >&2
  exit 2
fi

old_hermes_target=$(readlink "${hermes_link}")
old_current_target=
if [[ -L ${current} ]]; then
  old_current_target=$(readlink "${current}")
fi
interface_was_active=0
if systemctl is-active --quiet "${interface_unit}"; then
  interface_was_active=1
fi
active_services=()
for service in "${mapped_services[@]}"; do
  if systemctl is-active --quiet "${service}"; then
    active_services+=("${service}")
  fi
done

timestamp=$(date -u +%Y%m%dT%H%M%SZ)
backup=/var/backups/potato-agent/hermes-lite-cutover/${timestamp}-${release_id}
install -d -o root -g root -m 0700 "${backup}"
install -d -o root -g root -m 0700 "${backup}/units" "${backup}/code-overwritten"
cp -a "${mapping}" "${backup}/users_mapping.yaml"
for service in "${mapped_services[@]}"; do
  cp -a "/etc/systemd/system/${service}" "${backup}/units/${service}"
done
printf '%s\n' "${old_hermes_target}" >"${backup}/old-hermes-target.txt"
printf '%s\n' "${old_current_target}" >"${backup}/old-current-target.txt"
printf '%s\n' "${active_services[@]}" >"${backup}/active-hermes-services.txt"
printf '%s\n' "${interface_was_active}" >"${backup}/interface-was-active.txt"
if [[ -f ${interface_dropin} && ! -L ${interface_dropin} ]]; then
  cp -a "${interface_dropin}" "${backup}/interface-dropin.conf"
elif [[ -e ${interface_dropin} || -L ${interface_dropin} ]]; then
  echo "error: interface Lite drop-in is not a regular file" >&2
  exit 2
fi

atomic_symlink() {
  local target=$1
  local destination=$2
  local temporary
  temporary=$(dirname "${destination}")/.$(basename "${destination}").cutover.$$
  rm -f "${temporary}"
  ln -s "${target}" "${temporary}"
  mv -Tf "${temporary}" "${destination}"
}

cutover_started=0
rollback() {
  local incoming=$?
  local rc=${1:-${incoming}}
  trap - ERR INT TERM
  if [[ ${cutover_started} -eq 0 ]]; then
    exit "${rc}"
  fi
  set +e
  echo "cutover failed; restoring legacy runtime from ${backup}" >&2
  systemctl stop "${interface_unit}"
  for service in "${mapped_services[@]}"; do
    systemctl stop "${service}"
  done
  for service in "${mapped_services[@]}"; do
    cp -a "${backup}/units/${service}" "/etc/systemd/system/${service}"
  done
  if [[ -f ${backup}/interface-dropin.conf ]]; then
    cp -a "${backup}/interface-dropin.conf" "${interface_dropin}"
  else
    rm -f "${interface_dropin}"
  fi
  atomic_symlink "${old_hermes_target}" "${hermes_link}"
  if [[ -n ${old_current_target} ]]; then
    atomic_symlink "${old_current_target}" "${current}"
  else
    rm -f "${current}"
  fi
  if find "${backup}/code-overwritten" -type f -print -quit | grep -q .; then
    rsync -a --chown=root:potato-interface \
      "${backup}/code-overwritten/" "${repo}/"
  fi
  chown root:potato-interface "${repo}"
  chmod 0750 "${repo}"
  systemctl daemon-reload
  for service in "${active_services[@]}"; do
    systemctl start "${service}"
  done
  if [[ ${interface_was_active} -eq 1 ]]; then
    systemctl start "${interface_unit}"
  fi
  printf 'rolled_back\n' >"${backup}/result.txt"
  exit "${rc}"
}
trap rollback ERR
trap 'rollback 130' INT TERM

cutover_started=1
echo "captured ${#active_services[@]} active Hermes service(s) before cutover"
if [[ ${interface_was_active} -eq 1 ]]; then
  systemctl stop "${interface_unit}"
fi
for service in "${active_services[@]}"; do
  systemctl stop "${service}"
done
for service in "${active_services[@]}"; do
  if systemctl is-active --quiet "${service}"; then
    echo "error: Hermes service did not stop: ${service}" >&2
    false
  fi
done
if systemctl is-active --quiet "${interface_unit}"; then
  echo "error: interface service did not stop" >&2
  false
fi
if pgrep -f '[t]ui_gateway.entry|[s]lash_worker' >"${backup}/unexpected-gateway-processes.txt"; then
  echo "error: a TUI gateway or slash worker remained after stop" >&2
  false
fi

if ! "${interface_python}" -B "${fingerprint_script}" capture \
  --mapping "${mapping}" \
  --data-dir "${data_dir}" \
  --output "${backup}/state-before.json"; then
  echo "error: pre-cutover state fingerprint failed" >&2
  rollback 2
fi

rsync -a \
  --chown=root:potato-interface \
  --chmod=Dgo-w,Fgo-w \
  --backup \
  --backup-dir="${backup}/code-overwritten" \
  "${code_source}/" "${repo}/"
chown root:potato-interface "${repo}"
chmod 0750 "${repo}"

atomic_symlink "${release}" "${current}"
atomic_symlink "${current}/venv/bin/hermes" "${hermes_link}"

install -d -o root -g root -m 0755 "$(dirname "${interface_dropin}")"
dropin_temp=${interface_dropin}.cutover.$$
printf '%s\n' \
  '[Service]' \
  'Environment=INTERFACE_TUI_GATEWAY_PYTHON=/opt/potato-hermes-lite/current/venv/bin/python3' \
  >"${dropin_temp}"
chown root:root "${dropin_temp}"
chmod 0644 "${dropin_temp}"
mv -Tf "${dropin_temp}" "${interface_dropin}"

if PYTHONPATH="${repo}" \
  POTATO_AGENT_MAPPING_PATH="${mapping}" \
  "${interface_python}" -B "${refresh_script}" \
    --all \
    --expect-count "${expected_count}" \
    --require-existing-set \
    >"${backup}/unit-refresh-check.log" 2>&1; then
  refresh_check_rc=0
else
  refresh_check_rc=$?
fi
if [[ ${refresh_check_rc} -ne 0 && ${refresh_check_rc} -ne 1 ]]; then
  echo "error: Hermes unit preflight failed" >&2
  false
fi

PYTHONPATH="${repo}" \
POTATO_AGENT_MAPPING_PATH="${mapping}" \
"${interface_python}" -B "${refresh_script}" \
  --apply \
  --all \
  --expect-count "${expected_count}" \
  --require-existing-set \
  >"${backup}/unit-refresh-apply.log" 2>&1

if ! "${interface_python}" -B "${fingerprint_script}" capture \
  --mapping "${mapping}" \
  --data-dir "${data_dir}" \
  --output "${backup}/state-after.json"; then
  echo "error: post-cutover state fingerprint failed" >&2
  rollback 2
fi
if ! "${interface_python}" -B "${fingerprint_script}" compare \
  --before "${backup}/state-before.json" \
  --after "${backup}/state-after.json" \
  >"${backup}/state-compare.json"; then
  echo "error: protected state changed during cutover" >&2
  rollback 2
fi

for service in "${active_services[@]}"; do
  systemctl start "${service}"
  systemctl is-active --quiet "${service}"
done
if [[ ${interface_was_active} -eq 1 ]]; then
  systemctl start "${interface_unit}"
  systemctl is-active --quiet "${interface_unit}"
  health_ok=0
  for _attempt in $(seq 1 40); do
    if curl -fsS http://127.0.0.1:3000/health >"${backup}/interface-health.json"; then
      health_ok=1
      break
    fi
    sleep 0.25
  done
  if [[ ${health_ok} -ne 1 ]]; then
    echo "error: interface health check failed" >&2
    false
  fi
fi

interface_pid=$(systemctl show "${interface_unit}" --property=MainPID --value)
if [[ ${interface_was_active} -eq 1 ]]; then
  interface_python_env=$(tr '\0' '\n' <"/proc/${interface_pid}/environ" | sed -n 's/^INTERFACE_TUI_GATEWAY_PYTHON=//p')
  if [[ ${interface_python_env} != "${current}/venv/bin/python3" ]]; then
    echo "error: interface did not activate the Lite gateway Python" >&2
    false
  fi
fi
for service in "${active_services[@]}"; do
  service_pid=$(systemctl show "${service}" --property=MainPID --value)
  service_command=$(tr '\0' ' ' <"/proc/${service_pid}/cmdline")
  if [[ ${service_command} != *"${release}/venv/bin/python3"* ]]; then
    echo "error: service did not start from Lite venv: ${service}" >&2
    false
  fi
done
if pgrep -f '[s]lash_worker' >"${backup}/unexpected-slash-workers.txt"; then
  echo "error: legacy slash worker appeared after cutover" >&2
  false
fi

"${current}/venv/bin/pip" check >"${backup}/lite-pip-check.txt"
"${hermes_link}" --help >"${backup}/lite-hermes-help.txt"
printf 'complete\n' >"${backup}/result.txt"
trap - ERR INT TERM

echo "Lite cutover complete"
echo "backup: ${backup}"
echo "restored Hermes services: ${#active_services[@]}"
